services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: anidex
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "80:3000"
    env_file:
      - .env.prod
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge