import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Anidex - Anime Community",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`min-h-screen bg-neutral-800 px-4 md:px-6 text-neutral-50 ${inter.className}`}
            >
                <header className="z-50 top-0 left-0 right-0 fixed w-full bg-transparent">
                    <div className="max-w-[1800px] mx-auto px-5 py-3 flex justify-between items-center">
                        <Image src="/anidex-logo.png" alt="anidex logo" width={50} height={50} />
                        <Button variant="secondary" className="bg-primary font-semibold">
                            Login
                        </Button>
                    </div>
                </header>
                {children}
            </body>
        </html>
    );
}
