import type { Metadata } from "next";
import { Inter, Prompt, Rowdies } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });
const rowdies = Rowdies({
    subsets: ["latin"],
    weight: "700",
});

export const metadata: Metadata = {
    title: "AniDex - Anime Community",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`min-h-screen max-w-[1800px] mx-auto bg-neutral-800 px-4 md:px-10 3xl:px-2 text-neutral-50 ${inter.className}`}
            >
                <Header rowdies={rowdies} />
                {children}
                <SpeedInsights />
            </body>
        </html>
    );
}
